### ISSUE TITLE
How to actually use?

### ISSUE THREAD

**Issue by fxfactorial** [gtk2hs/gtk-mac-integration#1]
Just trying to clear up some confusions.

I'm sticking with gtk3, so I did 

`cabal install gtk3-mac-integration`, 

but got the exception, since cabal is not a package manager, that gtk-mac-integration is not found. Fair enough, but just to be clear gtk-mac-integration refers to this, https://github.com/jralls/gtk-mac-integration

correct?  and not to cabal install gtk-mac-integration? 

(I was hoping that brew would have gtk-mac-integration available, but sadly it doesn't. )

I tried installing gtk-mac-integration, but not clear on what to do afterwards (it creates some jhbuild tools/directories, etc)

**Comment by hamishmack** [comment]
Yes that is correct.  "cabal install gtk-mac-integration" would just install the Gtk+2 version of the Haskell wrappers.

**Comment by fxfactorial** [comment]
Thanks.
