### ISSUE TITLE
applicationGetUseQuartsAccelerators et al misspell "Quartz"

### ISSUE THREAD

**Issue by rcook** [gtk2hs/gtk-mac-integration#3]
Typo: `applicationGetUseQuartsAccelerators` ought to be `applicationGetUseQuartzAccelerators` and `applicationSetUseQuartsAccelerators` ought to be `applicationSetUseQuartzAccelerators`.

https://github.com/gtk2hs/gtk-mac-integration/blob/master/Graphics/UI/Gtk/OSX/Application.chs#L94

Perhaps gtk-mac-integration should expose both for backwards compatibility.

**Comment by hamishmack** [comment]
Doh!  Sorry about that.

**Comment by rcook** [comment]
You'll want to take commit d6e93ec0897cac53d6dfd6cd4a5856909133a91f, not the other. The other is simply the same commit rebased on top of some other stuff I'm working on.
